In [19]:
import numpy as np # import the library
a = np.arange(20) # define an array with 20 elements
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
# creat specific array
a = np.zeros(20)
b = np.ones(20)
c = np.zeros(b.size)+6
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [26]:

a = np.random.rand(20) #define an array with 20 random numbers from 0 to 1
print(a) # print it
print(a*5) # generate a random array from 0 to 5

[0.89866591 0.62896362 0.57184752 0.33284304 0.17135501 0.27851687
 0.19097854 0.77469462 0.68241903 0.17213917 0.30845504 0.00648667
 0.45740978 0.4029213  0.33722549 0.88699106 0.49094119 0.2473839
 0.70436339 0.97753199]
[4.49332957 3.1448181  2.85923761 1.66421522 0.85677507 1.39258435
 0.95489269 3.87347311 3.41209517 0.86069585 1.54227519 0.03243336
 2.28704889 2.01460648 1.68612744 4.43495532 2.45470597 1.2369195
 3.52181697 4.88765995]


In [30]:

# use random numbers to populate an array
a = np.arange(20) # define an array with 20 elements
print(a) # print it
print(a[-1]) # print the last element
print(a[1:5]) # print the element from index 1 to 5
print(a[1:10:3])# print the element from index 1 to 10 with skip 2 elements

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
19
[1 2 3 4]
[1 4 7]


In [34]:
# print index of the array
a = np.zeros((5, 10))## difine an 2D array, 

print(a, '\n')

# shape of the array
print('len =',len(a)) # get the rows
print('len =' , len(a[0]))# get the cols
print('shape =',a.shape) # get the size

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

len = 5
len = 10
shape = (5, 10)


In [38]:
# pick two output valuables from a method
a = np.zeros((6,12))## difine an 2D array
nx,ny = a.shape # get the length in row and col
print('nx =', nx) # print the length of row
print('ny =', ny) # print the length of col

nx = 6
ny = 12


In [42]:
# ways to generate a constant array
a = np.zeros((5,10)) + 6 ## difine an 2D (5,10) array each zero + 6
print(a, '\n')

b = np.ones((5,10)) * 7 # difine an 2D (5,10) array each zero * 7
print(b, '\n')

c = np.full((5,10),8) # difine an 2D (5,10) array with 8
print(c)

[[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]] 

[[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]] 

[[8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]]


In [43]:
# identity matrix function eye()
# identity matrix function eye()
a = np.eye(10) #  # difine an 2D (10,10) array, diagonal is 1
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [45]:
# index
a = np.array(([1,2,3], [3,4,5], [5,6,7])) # difine an 2D (3,3) array, each element was defined
print(a)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [47]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # difine an 2D (3,4) array, each element was defined
print(a)
b = a[:3, 1:3] # b is subset of a, the row is 0-3, col is 1-3
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [48]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # difine an 2D (3,4) array, each element was defined
print(a)
b = a[1, :] # b is subset of a, pick the second row
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [49]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]]) # output [0,2], [1,1], [2,2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


In [50]:
# update values
a = np.zeros((3,3))
for i in range(3):# for loop
    a[:,i] = i
print('before\n',a)

a[1,:] += 10 # add 10 to the second row
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


In [51]:
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.# change the element value in third col
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In [52]:
# type of data in the array
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype) # print the data type of elements of a

[[1 1]
 [1 1]]
int32


In [53]:

a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype) # print the data type of elements of a

[[1. 1.]
 [1. 1.]]
float64


In [54]:

a=np.array(([1.,1],[1,1]))>2
print(a) # print true of elements of a > 2
print(a.dtype) # print the data type of elements of a

[[False False]
 [False False]]
bool


In [55]:

a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)  # print the data type of elements of a

[['1' '1']
 ['1' '1']]
<U1


In [57]:
a=np.array((['1','1'],['1','1']),dtype=float) # define the data type is float
print(a)
print(a.dtype) # print the data type of elements of a

[[1. 1.]
 [1. 1.]]
float64


In [61]:
# most numpy functions can be applied directly to an array
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print(a)
print(a >= 1) # if elements of a > 1, return true, else return false
print(np.sqrt(a)) # calculate the sqrt root of every elements

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[False  True  True]
 [False  True  True]
 [False  True  True]]
[[0.         1.         1.41421356]
 [0.         1.         1.41421356]
 [0.         1.         1.41421356]]


In [62]:
# inversion
A = np.matrix([[1,0,0],
               [0,1,0],
               [0,0,1]])# define a matrix

B = np.matrix([[3,1],
               [1,3]])

print(A, '\n')
print(np.trace(A), '\n') # print tarce of a 
print(np.invert(A), '\n') # print invert of a 

print(B, '\n')
print(np.trace(B), '\n') # print tarce of b
print(np.invert(B))      # print invert of b 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

3 

[[-2 -1 -1]
 [-1 -2 -1]
 [-1 -1 -2]] 

[[3 1]
 [1 3]] 

6 

[[-4 -2]
 [-2 -4]]


In [63]:
# numpy.linalg.eig(a)     Calculate the eigenvalues and eigenvectors of the square matrix.
# numpy.linalg.eigvals(a) Calculate the eigenvalues of the square matrix.

x = np.diag([1,2,3])
print(np.linalg.eigvals(x))

a, b = np.linalg.eig(x)
print('eigenvalue：', a, '\n')
print('eigenvector：\n', b, '\n')


# verify that the eigenvalues and eigenvectors are correct
for i in range(3):       
    if np.allclose(a[i] * b[:, i], np.dot(x, b[:, i])):
        print('Correct')
    else:
        print('Wrong')

[1. 2. 3.]
eigenvalue： [1. 2. 3.] 

eigenvector：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Correct
Correct
Correct


In [64]:
# two arrays
a = np.zeros((3,3))
b = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
    b[i,:] = i
print('a=\n', a)
print('b=\n', b)

print('a+b=\n', a + b)
print('a*b=\n', a * b)
print('a/b=\n', a / b) # notice the first row of the result

a=
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
b=
 [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]
a+b=
 [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
a*b=
 [[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
a/b=
 [[nan inf inf]
 [0.  1.  2. ]
 [0.  0.5 1. ]]


In [65]:
# broadcasting
# add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([2, 0, 1])
y = x + v # print  x + v in each element
z = x * v # print  x * v in each element
print(y, '\n')
print(z)

[[ 3  2  4]
 [ 6  5  7]
 [ 9  8 10]
 [12 11 13]] 

[[ 2  0  3]
 [ 8  0  6]
 [14  0  9]
 [20  0 12]]


In [66]:

# dot product
x = np.array([1,2,3,4,5])
y = np.array([2,3,4,5,6])
z = np.dot(x,y)  #  The dot product of two vectors
print(z) # print the dot product of x and y

x = np.array([[1,2,3],[3,4,5],[6,7,8]])
y = np.array([[5,4,2],[1,7,9],[0,4,5]])
z= np.dot(x,y)   #  matrix multiplication
print(z) # print the dot product of x and y

70
[[  7  30  35]
 [ 19  60  67]
 [ 37 105 115]]


In [70]:
a = np.array([1,2])
b = np.array([3,4]) 
c = np.array([[3],[4]])

print(b*a) # print the result of b * a
print(a*c)  # print the result of a * c
            #  A matrix multiplies its elements, so it satisfies the commutative law

print(c*a)

print(np.dot(a,b))    #  matrix multiplication
print(np.dot(a,c))
# print(np.dot(c,a)) #There will be an error

[3 8]
[[3 6]
 [4 8]]
[[3 6]
 [4 8]]
11
[11]


In [74]:

# cross product
a = [3,4,5]
b = [5,6,7]

c = np.cross(a,b) 
print(c)  # print the cross product of a and b

[-2  4 -2]


In [72]:
# matrix multiplication
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

c = np.matmul(a,b)
print(c)

[[10 13]
 [22 29]]


In [75]:
# transpose
a = np.array(([1,2], [3,4],[ 5,6]))
print('a=\n',a) # print a
print('a.T=\n',a.T) # print transposed a
print('a.transpose()=\n',a.transpose())

a=
 [[1 2]
 [3 4]
 [5 6]]
a.T=
 [[1 3 5]
 [2 4 6]]
a.transpose()=
 [[1 3 5]
 [2 4 6]]


In [76]:
# reshape
a = np.array(([1,2], [3,4], [5,6])) # define a in 3 rows and 2 cols
print('a\n', a)

b = a.reshape((2,3)) # reshape a in 2 rows and 3 cols
print('b\n', b)

c = a.flatten() # reshape a as 1 row
print('c\n', c)

# C order, row order
d = a.flatten(order = 'C') 
print('d\n', d)

# Fortran order, column order
e = a.flatten(order = 'F')
print('e\n', e)

a
 [[1 2]
 [3 4]
 [5 6]]
b
 [[1 2 3]
 [4 5 6]]
c
 [1 2 3 4 5 6]
d
 [1 2 3 4 5 6]
e
 [1 3 5 2 4 6]


In [77]:
# stacking
a=np.full((3,2),1.) # define a as 3 rows and 2 cols with 1
b=np.full((3,2),2.) # define b as 3 rows and 2 cols with 2
c=np.full((3,2),3.) # define c as 3 rows and 2 cols with 3

print('a=',a)
print('b=',b)
print('c=',c)

print('hstack=',np.hstack((a,b,c))) 
print('vstack=',np.vstack((a,b,c)))

a= [[1. 1.]
 [1. 1.]
 [1. 1.]]
b= [[2. 2.]
 [2. 2.]
 [2. 2.]]
c= [[3. 3.]
 [3. 3.]
 [3. 3.]]
hstack= [[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]]
vstack= [[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [85]:
# difference of python sum and numpy.sum

data = np.arange(1000)

%timeit sum(data)# timing sum all elements of data
%timeit np.sum(data)

164 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
7.37 µs ± 60.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [89]:

a = np.array([[8, -6, 2], [-4, 11, -7], [4, -7, 6]])
b = np.array([[28], [-40], [33]])
x = np.linalg.solve(a, b)
print(a)
print(x)

[[ 8 -6  2]
 [-4 11 -7]
 [ 4 -7  6]]
[[ 2.]
 [-1.]
 [ 3.]]


In [90]:

m = np.array([[1, -2, 1],[0, 2, -8],[-4, 5, 9]])
v = np.array([0, 8, -9])
r = np.linalg.solve(m, v) # solve the function
print('result：')
name = ['X1', 'X2', 'X3']
for i in range(len(name)):
    print(name[i] + '=' + str(r[i]))

result：
X1=29.0
X2=16.0
X3=3.0


In [91]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,1])
try:
    npl.solve(mat,sol)
except:
    print(np.hstack([mat,sol]))
    print('Not solveable. Adding rows 1 and 2 contradicts row 3.')

[[ 1  1  1  3]
 [ 1 -1  2  2]
 [ 2  0  3  1]]
Not solveable. Adding rows 1 and 2 contradicts row 3.


In [92]:
# (whether all eigenvalues are positive)
A = np.arange(16).reshape(4,4)
print(A)

A = A + A.T  # Convert square matrices to symmetric matrices
print(A)

B = np.linalg.eigvals(A)
print(B)

if np.all(B>0):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01+0.00000000e+00j -7.41657387e+00+0.00000000e+00j
 -8.88285420e-17+1.82759332e-15j -8.88285420e-17-1.82759332e-15j]
No


In [93]:
#coding:utf8

def gram_schmidt(A):
    """Gram-schmidt Orthogonalization"""
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) 
        e = u / np.linalg.norm(u)  # normalization 
        Q[:, cnt] = e
        cnt += 1
    R = np.dot(Q.T, A)
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = gram_schmidt(A)
print(Q)
print(R)
print(np.dot(Q, R))

[[ 0.647   0.5096  0.1799]
 [ 0.5392 -0.4811  0.5743]
 [ 0.5392 -0.1305 -0.7902]
 [ 0.      0.7013  0.1162]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [  0.   4.   3.]]


In [94]:
def givens_rotation(A):
    """"Givens Rotations"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(r, -1, c)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:  
            r_ = np.hypot(R[col, col], R[row, col])  # d
            c = R[col, col]/r_
            s = -R[row, col]/r_
            G = np.identity(r)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)   # R=G(n-1,n)*...*G(2n)*...*G(23,1n)*...*G(12)*A
            Q = np.dot(Q, G.T)  # Q=G(n-1,n).T*...*G(2n).T*...*G(23,1n).T*...*G(12).T
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = givens_rotation(A)
print(Q)
print(R)
print (np.dot(Q, R))

[[ 0.647   0.5096  0.1799 -0.5379]
 [ 0.5392 -0.4811  0.5743  0.3848]
 [ 0.5392 -0.1305 -0.7902  0.2607]
 [ 0.      0.7013  0.1162  0.7034]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]
 [-0.     -0.      0.    ]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [ -0.   4.   3.]]


In [95]:
def householder_reflection(A):
    """Householder Triangularization"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    for cnt in range(r - 1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)  # R=H(n-1)*...*H(2)*H(1)*A
        Q = np.dot(Q, Q_cnt)  # Q=H(n-1)*...*H(2)*H(1)  H is the self inverse matrix
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = householder_reflection(A)
print(Q)
print(R)
print(np.dot(Q, R))

[[ 0.647   0.5096  0.1799  0.5379]
 [ 0.5392 -0.4811  0.5743 -0.3848]
 [ 0.5392 -0.1305 -0.7902 -0.2607]
 [ 0.      0.7013  0.1162 -0.7034]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]
 [ 0.      0.     -0.    ]]
[[  6.   5.  -0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [ -0.   4.   3.]]


In [96]:
# creating a 1-D list (Horizontal)
list1 = [5, 6, 9]
 
# creating a 1-D list (Horizontal)
list2 = [1, 2, 3]

# creating first vector
vector1 = np.array(list1)
 
# printing vector1
print("First Vector   : " + str(vector1))
 
# creating second vector
vector2 = np.array(list2)
 
# printing vector2
print("Second Vector  : " + str(vector2))

addition = vector1 + vector2
 
# printing addition vector
print("Vector Addition: " + str(addition))

scalarmult = 2 * vector1

# printing scalar multiplication vector
print("Vector Addition: " + str(scalarmult))

# as long as vector1 and vector2 belongs to U, 
# addition vector and scalarmult vector both belongs to U

First Vector   : [5 6 9]
Second Vector  : [1 2 3]
Vector Addition: [ 6  8 12]
Vector Addition: [10 12 18]
